#:import BlockLabel ui.api.block_label.BlockLabel

<SplashScreen>:
    BoxLayout:
        orientation: 'vertical'

        AsyncImage:
            source: 'assets/images/icon.png'

        BlockLabel:
            text: 'Loading'
            size_hint: 1, .2
            markup: True

            canvas.before:
                Color:
                    rgba: .8, .8, .8, .5
                Rectangle:
                    pos: self.pos
                    size: self.size
